{
 "title": "Telegraf Host Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(system_n_cpus, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average CPU",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time({__name__=~\"cpu_.*\", cpu=\"cpu-total\", host=\"$host\"}[$__range])",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(mem_used_percent{host=\"$host\"}[$__range])",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Average Swap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(swap_used_percent{host=\"$host\"}[$__range])",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Average Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(disk_used_percent{host=\"$host\"}[$__range])",
     "legendFormat": "{{__name__}} {{path}}"
    }
   ]
  },
  {
   "title": "Average Disk Inodes Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(disk_inodes_used{host=\"$host\"}[$__range]) / avg_over_time(disk_inodes_total{host=\"$host\"}[$__range]) * 100",
     "legendFormat": "{{device}} {{path}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"cpu_.*\", cpu=\"cpu-total\", host=\"$host\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"(mem_|swap_)(used|total)\", host=\"$host\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(net_bytes_recv{host=\"$host\"})",
     "legendFormat": "net_bytes_recv {{interface}}"
    },
    {
     "expr": "- rate(net_bytes_sent{host=\"$host\"})",
     "legendFormat": "net_bytes_sent {{interface}}"
    }
   ]
  },
  {
   "title": "Processes Info",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time({__name__=~\"processes_.*\", host=\"$host\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"system_load.*\", host=\"$host\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"disk_(used|total)\", host=\"$host\"}",
     "legendFormat": "{{__name__}}  {{path}}"
    }
   ]
  },
  {
   "title": "Docker Container Average CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sum by (container_name)(docker_container_cpu_usage_percent{host=\"$host\"}[$__range]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Docker Container Average Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sum by (container_name)(docker_container_mem_usage_percent{host=\"$host\"}[$__range]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Top 30 Processes Average CPU Usage",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(30, procstat_cpu_usage{host=\"$host\"})",
     "legendFormat": "{{user}} {{pid}} {{process_name}} @ {{cmdline}}"
    }
   ]
  },
  {
   "title": "Top 30 Processes Average Memory Usage",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(30, procstat_memory_usage{host=\"$host\"})",
     "legendFormat": "{{user}} {{pid}} {{process_name}} @ {{cmdline}}"
    }
   ]
  },
  {
   "title": "Processes Average CPU Usage",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "procstat_cpu_usage{host=\"$host\"}",
     "legendFormat": "{{user}} {{pid}} {{process_name}} @ {{cmdline}}"
    }
   ]
  },
  {
   "title": "Processes Average Memory Usage",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "procstat_memory_usage{host=\"$host\"}",
     "legendFormat": "{{user}} {{pid}} {{process_name}} @ {{cmdline}}"
    }
   ]
  }
 ]
}