create database nocodb;
create database openproject;
create database gitlab;
create database strapi;
create database nextcloud;
create user nocodb with password '${NOCODB_SQL_PASSWORD}';
create user openproject with password '${OPENPROJECT_SQL_PASSWORD}';
create user gitlab with password '${GITLAB_SQL_PASSWORD}';
create user strapi with password '${STRAPI_SQL_PASSWORD}';
create user nextcloud with password '${NEXTCLOUD_SQL_PASSWORD}';
grant all privileges on database nocodb to nocodb;
grant all privileges on database openproject to openproject;
grant all privileges on database gitlab to gitlab;
grant all privileges on database strapi to strapi;
grant all privileges on database nextcloud to nextcloud;
